### ISSUE TITLE
Configure cluster topology from replicasets.yml

### ISSUE THREAD

**Issue by vrogach2020** [tarantool/cartridge-java-testcontainers#27]
subj

**Comment by ArtDu** [comment]
This is necessary at least because now the retry on eval `cartridge.admin_edit_topology` doesn't work correctly and there are some problems with it

Problems:
1) setupTopology doesn't return an error or result
  https://github.com/tarantool/cartridge-java-testcontainers/blob/a9f9593d23ea6ed6b69003e4b456de26ee5df966/src/main/java/org/testcontainers/containers/TarantoolCartridgeContainer.java#L453-L455
  https://github.com/tarantool/cartridge-java-testcontainers/blob/a9f9593d23ea6ed6b69003e4b456de26ee5df966/src/main/java/org/testcontainers/containers/TarantoolContainerClientHelper.java#L61-L78

2) `cartridge.admin_edit_topology` always drops socket connections when it apply topology. Because connection to the router (eval) will fall we will not be able to get in java the result of function in cartridge-java-testcontainers
  https://github.com/tarantool/cartridge/blob/master/cartridge/confapplier.lua#L551-L556

It follows from these problems that such erroneous behavior, which I received, may appear. Some Instances may not have time to start, topology will be applied, cartridge-java-testcontainers will consider that eval was succesfull, because it will not get error or something. We will have an inconsistent cluster.


**How to reproduce**
Add in topology instance with non-existent address or port 

We can w/a it by still using `topology.lua`, but we should call two functions, one should apply topology, the other should check of succes of applying

**Comment by vrogach2020** [comment]
done in https://github.com/tarantool/cartridge-java-testcontainers/commit/a9bc5b072bb41f60f33292c69a41fee288a54b6f
